name: FreeMyXe Compiler

jobs:
  Xbox:
    if: github.repository == 'InvoxiPlayGames/FreeMyXe'
    runs-on: windows-2019
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download tools
        env:
          BUILD_TOOLS: ${{ secrets.BUILD_TOOLS_FILE }}
        run: |
          Invoke-WebRequest -OutFile tools.zip $Env:BUILD_TOOLS
          7z x tools.zip -otools

      - name: Compile
        env:
          XEDK: ${{ github.workspace }}/tools
        run: |
          make clean
          make -j2

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with: 
          name: FreeMyXe-Artifact
          path: out/FreeMyXe.xex
